config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  root :to => 'posts#index'
  
  resources :comments

  resources :categories

  resources :posts

  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :category_ids

  validates :user_id, :presence => true
  validates :title,   :presence => true
  validates :content, :presence => true

  belongs_to :user
  has_many :category_posts, :dependent => :destroy
  has_many :categories, :through => :category_posts
  has_many :comments, :as => :commentable, :dependent => :destroy 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    # @posts = Post.all
    @posts = Post.order("title").page(params[:page]).per(5)
  end
 
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end
 
  def new
    @post = Post.new
  end
 
  def edit
    @post = Post.find(params[:id])
  end
 
  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    @post.save ? redirect_to(@post, :notice => 'Post was successfully created.') : render(:action => "new")
  end
 
  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post]) ? redirect_to(@post, :notice => 'Post was successfully updated.') : (render :action => "edit")
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy and redirect_to(posts_url)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="comment">
  <div class="comment-header">
    <b><%= comment.title %></b><br />
    posted by <%= link_to comment.user.login, comment.user %>,
    posted at: <%= comment.created_at.to_formatted_s(:short)%>
    <% if comment.user == current_user %>
      <%= link_to("delete", comment_path(comment, { :post_id => @post.id }), :method => :delete) %>
    <% end %>
  </div>
  <div class="comment-text">
    <%= comment.comment %>
    <br />
    <%= link_to "reply", new_comment_path({:comment => {:commentable_id => comment.id, :commentable_type => "Comment"}, :post_id => @post.id }) if user_signed_in? %>
  </div>
  <%= render :partial => "comment", :collection => comment.comments %>
</div>

app/views/posts/_comments.html.erb
<div id = 'comments'>
  <h3><%= @post.comments_counter %> Comments</h3>
  <hr />
  <%= render :partial => "comment", :collection => @post.comments %>
</div>

app/views/posts/_comments_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :size => "67x5"%>
  </div>
  <% unless params[:comment] && params[:comment][:commentable_id] && params[:comment][:commentable_type] %>
    <%= f.hidden_field :commentable_id, :value => @post.id %>
    <%= f.hidden_field :commentable_type, :value => "Post" %>
  <% else %>
    <%= f.hidden_field :commentable_id, :value => params[:comment][:commentable_id] %>
    <%= f.hidden_field :commentable_type, :value => params[:comment][:commentable_type] %>
  <% end %>
  <%= hidden_field_tag :post_id, params[:post_id] ? params[:post_id] : @post.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="categories">
    <% @categories.each do |category| %>
      <div class="field">
        <%= check_box_tag 'post[category_ids][]', category.id, @post.category_ids.include?(category.id) %>
        <%= label 'post', 'category_ids', h(category.name), :value => category.id %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= paginate @posts %>
<span class = 'new-link'><%= link_to 'New Post', new_post_path if user_signed_in? %></span>

<% @posts.each do |post| %>
  <h1 class = 'post-title'>
    <%= link_to post.title, post %>
  </h1>

  <% if current_user == post.user %>
    <span class = 'post-menu'>Posted by <%= link_to post.user.login, post.user %> |
      <%= link_to 'edit', edit_post_path(post), :class => 'edit-link' %>
      <%= link_to 'delete', post, :confirm => 'Are you sure?', :method => :delete, :class => 'delete-link' %>
    </span>
  <% end %>

  <%= post.content %>

  <br />
  
  <hr />
  <% end %>
<br />

<%= paginate @posts %>
<span class = 'new-link'><%= link_to 'New Post', new_post_path if user_signed_in? %></span>

app/views/posts/new.html.erb
<h1>New post</h1>
<b>User:</b> <%= current_user.login %>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class = 'post-title'> <%= @post.title %> </h1>
<b>Posted by:</b> <%= link_to @post.user.login, @post.user %> |
<% if current_user == @post.user %>
  <%= link_to 'Edit', edit_post_path(@post) %>
<% end %>
<br />
<%= @post.content %>
<br />
<%= link_to 'Back', posts_path %>
<%= render 'comments' %>
<%= render 'comments_form' if user_signed_in? %>